version: '3.8'

services:
  fuseki:
    image: vitalai/kgraphdb:0.1.0
    ports:
      - "3030:3030"
    volumes:
      - ./fuseki-data:/fuseki-data
      - ./config.ttl:/fuseki/config.ttl
      - ./shiro.ini:/fuseki/shiro.ini
      - ./configuration:/fuseki/configuration
      - ./databases:/fuseki/databases

